name: Post welcome comment
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to the Repo" $First_Name "**********"
        env:
          First_Name:
          
      
